spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USER}
    password: ${EMAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: notification-service
  task:
    scheduling:
          pool:
            size: 5

aws:
  region: us-east-1
  accessKeyId:
  secretKey:
  dynamodb:
    endpoint: http://localhost:8000

dynamodb:
  table:
    name: notifications

logging:
  level:
    root: INFO
    service: DEBUG
    repository: DEBUG


notification:
  scheduler:
    interval: 10000   # 10 seconds
    max-retry: 3
twilio:
  account_sid: YOUR_SID
  auth_token: YOUR_TOKEN